sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: I5jRUORmMq+Y7mPpUAkmitYQT0odR3Q1o1fwHomQlpj78U02d/WyrF9jaB2m3n0RSUXmPjiHj6jf4chOEErBnAZa1PoDl3ec9rbReo2NuOqYSpmJsNxT8M8JViGK0hMsQKd1DitTJqwAh3DmyztgZLa4alNUKMz3N+PW0OWNXdSdip6irP29SjtPG/tuKCH5w2s7vKmZB+ZwXYcR2LoEioVcQulM0YDkYhlS2trmz9Qs92Qgu4scpWvVlI8yTrhLu5t/zHgZpatN350UMawohFYn/jVqeT++9/r/Y+YmicTr5HKPd2C4ZniuI8UkL58CHtDWvxLrqQ2zcvESRQ1zfSwt+6ykYVapJFVO4fyHluSJQYrq8SBsdPxzOAxZVxsy2Dfsv2LJx4pcH2ad/YcOLryc1x/xjy3OMsCNm77P465j2jKukWKXM4wMeivLsT2BF8edXjnc4SJV4swEnMfrDz7lfvlVHRg9EMb+ydcTV/j+ALxNc4xjFdgJTy4aWEi8A4YB+wjt72AXZ4jhORo97Q1WZkI9VaLK06+B8S+MUwn8g5Y/ssQNNN4MIuWiIn5UHX56zNlXPzDBFAEiOKCXhxHjGZ+1bjAErvofycB6cMdBmMKlE6SEZBYW8kid/VwD64L0PlqBeIgci7WK2E2N0ESHVdIR/zO7H1mEz6BK5XA=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Works-of-Edgar-Allan-Poe---Volume-3_2149
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy